import "AudioSessionSettings.idl";

namespace Croak
{
    [bindable]
    [default_interface]
    runtimeclass AudioProfile 
    {
        AudioProfile();

        String ProfileName;
        Windows.Foundation.Collections.IVector<AudioSessionSettings> AudioSessionsSettings;
        Windows.Foundation.Collections.IMap<String, UInt32> SessionsIndexes;
        Boolean IsDefaultProfile;
        Single SystemVolume;
        Boolean DisableAnimations;
        Boolean KeepOnTop;
        Boolean ShowMenu;
        UInt32 Layout;
        Boolean RestoreWindowState;
        Windows.Graphics.RectInt32 WindowDisplayRect;

        void Restore(Windows.Storage.ApplicationDataContainer container);
        void Save(Windows.Storage.ApplicationDataContainer container);
    }
}
