import "AudioSessionSettings.idl";
import "App.idl";

namespace Croak
{
    [bindable]
    [default_interface]
    runtimeclass AudioProfile 
    {
        AudioProfile();

        String ProfileName;
        AudioSessionSettings DefaultAudioEndpointSettings;
        Windows.Foundation.Collections.IVector<AudioSessionSettings> AudioSessionsSettings;
        Windows.Foundation.Collections.IMap<String, UInt32> SessionsIndexes;
        Boolean IsDefaultProfile;
        Boolean DisableAnimations;
        AudioSessionLayout Layout;
        Boolean ShowMenu;

        void Restore(Windows.Storage.ApplicationDataContainer container);
        void Save(Windows.Storage.ApplicationDataContainer container);
    }
}
