#pragma once
#include <mmdeviceapi.h>
#include <comdef.h>

// IMMDevicePtr
_COM_SMARTPTR_TYPEDEF(IMMDevice, __uuidof(IMMDevice));
// IMMDeviceEnumeratorPtr
_COM_SMARTPTR_TYPEDEF(IMMDeviceEnumerator, __uuidof(IMMDeviceEnumerator));
// IAudioSessionManager2Ptr
_COM_SMARTPTR_TYPEDEF(IAudioSessionManager2, __uuidof(IAudioSessionManager2));
// IAudioSessionManager2Ptr
_COM_SMARTPTR_TYPEDEF(IAudioSessionManager2, __uuidof(IAudioSessionManager2));
// IAudioSessionEnumeratorPtr
_COM_SMARTPTR_TYPEDEF(IAudioSessionEnumerator, __uuidof(IAudioSessionEnumerator));
// IAudioSessionControl2Ptr
_COM_SMARTPTR_TYPEDEF(IAudioSessionControl2, __uuidof(IAudioSessionControl2));
// IAudioSessionControlPtr
_COM_SMARTPTR_TYPEDEF(IAudioSessionControl, __uuidof(IAudioSessionControl));
// ISimpleAudioVolumePtr
_COM_SMARTPTR_TYPEDEF(ISimpleAudioVolume, __uuidof(ISimpleAudioVolume));
// IAudioSessionNotificationPtr
_COM_SMARTPTR_TYPEDEF(IAudioSessionNotification, __uuidof(IAudioSessionNotification));
// IAudioEndpointVolumePtr
_COM_SMARTPTR_TYPEDEF(IAudioEndpointVolume, __uuidof(IAudioEndpointVolume));
// IAudioMeterInformationPtr
_COM_SMARTPTR_TYPEDEF(IAudioMeterInformation, __uuidof(IAudioMeterInformation));