namespace Croak
{
    [bindable]
    [default_interface]
    runtimeclass HotkeyViewModel 
    {
        HotkeyViewModel();
        HotkeyViewModel(String hotKeyName, Boolean enabled, UInt32 key, UInt32 modifiers);

        String HotKeyName{ get; set; };
        Windows.System.VirtualKeyModifiers Modifiers{ get; set; };
        Windows.System.VirtualKey Key{ get; set; };
        Boolean IsHotKeyEnabled{ get; set; };
    }
}
