import "AudioViewer.idl";

namespace Croak
{
    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window
    {
        MainWindow(String args);

        static MainWindow Current{ get; };

        Windows.Graphics.RectInt32 DisplayRect{ get; };
        AudioViewer AudioViewer{ get; };
    }
}
