namespace Croak
{
    [bindable]
    [default_interface]
    runtimeclass NavigationBreadcrumbBarItem 
    {
        NavigationBreadcrumbBarItem();
        NavigationBreadcrumbBarItem(String displayName, Windows.UI.Xaml.Interop.TypeName itemTypeName);

        String DisplayName{ get; set; };
        Windows.UI.Xaml.Interop.TypeName ItemTypeName{ get; set; };
    }
}
